---
- hosts: ios-xe
  vars_files:
    - xe_vars.yaml
  tasks:
    - name: Merge provided configuration with device configuration
      cisco.ios.ios_vlans:
        config:
        - name: "{{ myvlan_name }}"
          vlan_id: "{{ myvlan_id }}"
          state: active
          shutdown: disabled
          remote_span: true
        state: merged