---
- hosts: ios-xe
  include_vars:
    file: xe_vars.yaml
  tasks:
    - name: Merge provided configuration with device configuration
      cisco.ios.ios_vlans:
        config:
        - name: Vlan_10
          vlan_id: 10
          state: active
          shutdown: disabled
          remote_span: true
        state: merged