
---
- hosts: webservers
  become: true
  tasks:
    - name: Set Hostname
      hostname:
        name: Webserver-{{groups['webservers'].index(inventory_hostname)}}

    - name: Install httpd
      become: true
      yum:
        name: 
          - apache2
          - python3-apt
        state: present

    - name: Add php repo
      become: true
      apt_repository:
        repo: 'ppa:ondrej/php'

    - name: Install php 8.0
      become: true
      yum:
        state: present
        name:
          - php8.0
          - libapache2-mod-php8.0
          - php8.0-zip
          - php8.0-curl
          - php8.0-mysql
          - php8.0-gd
          - php8.0-xml
          - php8.0-mcrypt
          - unzip
          - zip
          - curl


    - name: Download and Extract Opencart
      become: true
      unarchive:
        src: https://github.com/opencart/opencart/releases/download/2.3.0.2/2.3.0.2-compiled.zip
        dest: /var/www/html
        remote_src: yes

    - name: Copy sample config file
      command: cp -p /var/www/html/upload/config-dist.php /var/www/html/upload/config.php

    - name: Copy sample config file
      command: cp -p /var/www/html/upload/admin/config-dist.php /var/www/html/upload/admin/config.php

    - name: Delete content & directory
      file:
        state: absent
        path: /var/www/html/opencart/

    - name: Move upoload directory to opencart
      command:  mv /var/www/html/upload /var/www/html/opencart

    # - name: Update Opencart config file
    #   lineinfile:
    #     path: /var/www/html/Opencart/wp-config.php
    #     regexp: "{{item.regexp}}"
    #     line: "{{item.line}}"
    #  
    #   with_items:
    #     - {'regexp': "define\\( 'DB_NAME',(.)+\\);", 'line': "define( 'DB_NAME', 'Opencart' );"}
    #     - {'regexp': "define\\( 'DB_USER',(.)+\\);", 'line': "define( 'DB_USER', 'wpuser' );"}
    #     - {'regexp': "define\\( 'DB_PASSWORD',(.)+\\);", 'line': "define( 'DB_PASSWORD', 'cisco' );"}

    - name: Update ownership to Apache user
      file:
        path: /var/www/html
        state: directory
        recurse: yes
        owner: www-data
        group: www-data

    - name: Set the correct permissions for Opencart files
      file:        
        path: /var/www/html
        mode: 0755
        recurse: yes

    - name: start service
      service:
        name: apache2
        state: restarted

    - name: Run install on first webserver
      when: inventory_hostname == groups['webservers'][0]
      command: chdir=/var/www/html/opencart/install php /var/www/html/opencart/install/cli_install.php install --db_hostname {{ hostvars[groups['dbservers'][0]]['inventory_hostname'] }} --db_username ocuser --db_password cisco --db_database opencart --db_driver mysqli --db_port 3306 --username admin --password admin --email youremail@example.com --http_server http://{{ inventory_hostname }}/opencart/

    - name: Download sample config
      get_url:
        url: http://172.16.58.2/apps/config.php.sample
        dest: /tmp/config.php.sample

    - name: Update local server in Opencart config file
      replace:
        path: /tmp/config.php.sample
        regexp: '<OC_SERVER>'
        replace: '{{ inventory_hostname }}'

    - name: Update Database server in Opencart config file
      replace:
        path: /tmp/config.php.sample
        regexp: '<OC_DB_SERVER>'
        replace: '{{ hostvars[groups["dbservers"][0]]["inventory_hostname"] }}'

    - name: Update config file
      copy:
        src: /tmp/config.php.sample
        dest: /var/www/html/opencart/config.php
        remote_src: yes

